# Generated by Django 2.0.6 on 2018-06-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180607_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='upload', verbose_name='文章小图'),
        ),
    ]
