# Generated by Django 2.0.6 on 2018-06-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180610_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='合作伙伴')),
                ('href', models.URLField(verbose_name='合作伙伴链接')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (2, '删除')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '合作伙伴',
                'verbose_name_plural': '合作伙伴',
            },
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '友链', 'verbose_name_plural': '友链'},
        ),
    ]
