# Generated by Django 2.0.6 on 2018-06-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
