# Generated by Django 2.0.6 on 2018-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180618_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='编号')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='标题')),
                ('content', models.CharField(max_length=100, verbose_name='描述')),
                ('image', models.ImageField(upload_to='carousel', verbose_name='轮播图')),
                ('url', models.URLField(max_length=100, verbose_name='跳转地址')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['index', '-id'],
            },
        ),
    ]
